[phases.setup]
nixPkgs = [
  "php82", 
  "php82Packages.composer", 
  "nodejs_20", 
  "npm"
]

[phases.build]
cmds = [
  "composer install --no-interaction --prefer-dist --optimize-autoloader",
  "npm install",
  "npm run build"
]

[phases.start]
cmd = "php artisan migrate --force && php artisan config:cache && php artisan serve --host=0.0.0.0 --port=$PORT"
