[phases.setup]
nixPkgs = [
  "php82",
  "php82Packages.composer",
  "nodejs_20"
]

[phases.install]
cmds = [
  "composer install --no-interaction --prefer-dist --optimize-autoloader",
  "npm install"
]

[phases.build]
cmds = [
  "npm run build"
]

[phases.static_assets]
cmds = [
  "mkdir -p public/css public/vendor/bootstrap/css public/javaproyecto",
  "cp -r resources/static/css/* public/css/",
  "cp -r resources/static/js/* public/javaproyecto/",
  "cp -r node_modules/bootstrap/dist/css/bootstrap.min.css public/vendor/bootstrap/css/bootstrap.min.css"
]

[start]
cmd = "php artisan config:cache && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"
