[phases.setup]
nixPkgs = [
  "php82",
  "php82Packages.composer",
  "nodejs_20"
]

[phases.install]
cmds = [
  "composer install --no-interaction --prefer-dist --optimize-autoloader",
  "npm install"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "php artisan config:cache && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"
