[phases.setup]
nixPkgs = [
  "php82",
  "php82Packages.composer",
  "nodejs_20"
]

[phases.build]
cmds = [
  "composer install --no-interaction --prefer-dist --optimize-autoloader",
  "npm install",
  "npm run build"
]

[phases.start]
cmds = [
  "php artisan config:cache",
  "php artisan migrate --force",
  "php -S 0.0.0.0:$PORT -t public"
]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public"
